apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      version: 34.1.0
  interval: 5m
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
  rollback:
    timeout: 5m
    disableWait: false
    disableHooks: false
    recreate: false
    force: false
    cleanupOnFail: false
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: ServiceMonitor
            patch: |
              - op: replace
                path: /apiVersion
                value: azmonitoring.coreos.com/v1
              - op: add
                path: /spec/labelLimit
                value: 63
              - op: add
                path: /spec/labelNameLengthLimit
                value: 511
              - op: add
                path: /spec/labelValueLengthLimit
                value: 1023
  values:
    deployment:
      replicas: 3
      labels:
        release: traefik
      podAnnotations:
        linkerd.io/inject: enabled
        config.linkerd.io/skip-inbound-ports: 8000,8443
        config.linkerd.io/proxy-cpu-request: 50m
        config.linkerd.io/proxy-memory-limit: 250Mi
        config.linkerd.io/proxy-memory-request: 20Mi
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    ingressClass:
      enabled: true
    providers:
      kubernetesIngress:
        enabled: true
    globalArguments:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
    ports:
      web: null
      websecure: null
      http:
        port: 8000
        expose:
          default: true
        exposedPort: 80
        protocol: TCP
        redirections:
          entryPoint:
            to: https
            scheme: https
            permanent: true
        forwardedHeaders:
          insecure: true
      https:
        port: 8443
        expose:
          default: true
        exposedPort: 443
        protocol: TCP
        forwardedHeaders:
          insecure: true
        tls:
          enabled: true
          options: ""
          certResolver: ""
          domains: []
    tlsOptions:
      default:
        minVersion: VersionTLS12
        cipherSuites:
          - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
          - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
    tlsStore:
      default:
        defaultCertificate:
          secretName: ssl-cert
    resources:
      requests:
        cpu: "100m"
        memory: "50Mi"
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - traefik
              topologyKey: kubernetes.io/hostname
