apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certmanager
  namespace: flux-system
spec:
  sourceRef:
    kind: OCIRepository
    name: certmanager
  interval: 5m
  retryInterval: 5m
  path: ./
  prune: true
  wait: true
  timeout: 2m