apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certs
  namespace: flux-system
spec:
  dependsOn:
    - name: certmanager
      namespace: flux-system
  sourceRef:
    kind: OCIRepository
    name: certs
  interval: 5m
  retryInterval: 5m
  path: ./
  prune: true
  wait: true
  timeout: 2m