apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dummy
spec:
  patches:
    - target:
        kind: Certificate
      patch: |-
        - op: replace
          path: /spec/dnsNames/0
          value: "flux-staging.203.cloud"
    